export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const RESET_REGISTRATION_RESULT = 'RESET_REGISTRATION_RESULT';
export const SET_ERROR_TEXT = 'SET_ERROR_TEXT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';